M48
; DRILL file {KiCad 8.0.4} date 2024-11-26T16:04:48+0630
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-11-26T16:04:48+06:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.991
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X14.89Y54.55
X20.67Y54.55
T2
X20.955Y16.84
X21.971Y21.92
X22.987Y16.84
T3
X7.62Y55.88
X28.0Y55.88
M30
